### ISSUE TITLE
@PopperJS missing on fresh install

### ISSUE THREAD

**Issue by sistematico** [mralston/bootstrap-breeze#1]
```
ERROR in ./node_modules/bootstrap/dist/js/bootstrap.esm.js 6:0-41
Module not found: Error: Can't resolve '@popperjs/core' in '/home/lucas/github/somdomato.com/node_modules/bootstrap/dist/js'
```
Thank you.

**Comment by mralston** [comment]
Popper isn't part of the upstream `laravel/breeze` package. `mralston/bootstrap-breeze` is intended to be nothing more than a way to switch out Tailwind with Bootstrap in the Laravel Breeze starter pack. Other than the alternative CSS library, my intention is that the package should mirror `laravel/breeze`.

Popper was included as part of the default Laravel application install up until Laravel 5.8:

https://github.com/laravel/laravel/blob/5.8/package.json

From what I can see, it was dropped in Laravel 6:

https://github.com/laravel/laravel/blob/6.x/package.json

You should be able to add Popper to your installation using the following command:

```
npm install @popperjs/core
```
